### PR TITLE
Replace Appveyor by Github actions

### PR DESCRIPTION
**Pull request by skoudoro**
The goal is to create the wheel via Github Actions

### CODE REVIEW

**Comment by mattip** [comment]
Cool, this seems to be progressing. You might want to think about offering manylinux2010 for python3.8, you would need to set both `MB_ML_VER: "2010"` and `DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"` like [numpy-wheels does](https://github.com/MacPython/numpy-wheels/blob/master/azure-pipelines.yml#L60). 

Do you have any thoughts about arm64? github actions does not offer it yet.

**Comment by skoudoro** [comment]
Hi @mattip,

Thank you for the feedback!

> You might want to think about offering manylinux2010 for python3.8, you would need to set both MB_ML_VER: "2010" and DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}" like numpy-wheels does.

Will do on a new PR 👍 

> Do you have any thoughts about arm64? github actions does not offer it yet.

No idea at this moment. However, I plan to go to 2 directions:

1. [Azure Pipelines now supports Linux/ARM64](https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/). So I need to check how to use GitHub action for a specific runner.  I know that we can have a self-hosted runner so we should be able to use Azure.
2. I will explore [this action](https://github.com/uraimo/run-on-arch-action) on a specific PR. 
3. Since Github action depends on Azure and Azure supports now Linux/ARM64, I think it will come soon by default on Github actions

**Comment by mattip** [comment]
OK, although I am pretty sure the non-x86 support is [via QEMU](https://github.com/uraimo/run-on-arch-action/blob/master/src/run-on-arch.sh#L35) so I hope your build finishes before it times out.

**Comment by skoudoro** [comment]
Ok, LGTM, seems to works like a charm. 

manylinux2010 has been included for python 3.6-3.7-3.8. 

Todo in Future PRs:

- Figure out [the issue](https://github.com/MacPython/dipy-wheels/runs/1114978146#step:10:452) with libhdf5 and python3.8 on the x32 machines. No wheels exist for h5py and the compilation fails.
- Fix a DIPY test when numpy == 1.13.3. See issue https://github.com/dipy/dipy/issues/2216
- Add ARM64 matrix.

> OK, although I am pretty sure the non-x86 support is via QEMU so I hope your build finishes before it times out.

Indeed @mattip... Let's see! I hope option 1 (with Azure and Arm64) will be the way to go. I will start to look into it next week.


Merging !

**Pull request merged**
